export default {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAIL:    'FETCH_POSTS_FAIL',

    CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL:    'CREATE_TASK_FAIL',

    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL:    'DELETE_TASK_FAIL',

    UPDATE_TASKS_REQUEST: 'UPDATE_TASKS_REQUEST',
    UPDATE_TASKS_SUCCESS: 'UPDATE_TASKS_SUCCESS',
    UPDATE_TASKS_FAIL:    'UPDATE_TASKS_FAIL',
};
